repos:
-   repo: https://gitlab.com/vojko.pribudic.foss/pre-commit-update
    rev: v0.8.0
    hooks:
    -   id: pre-commit-update
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-toml
    -   id: check-added-large-files
-   repo: https://github.com/nestauk/pre-commit-hooks
    rev: v1.2.0
    hooks:
    -   id: nbstripout-preserve-timestamp
    -   id: jupytext-enforce-pairing
    -   id: jupytext-smart-sync
-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.13.3
    hooks:
    -   id: ruff-check
    -   id: ruff-format
