name: "Dynamic Badges"

on:
  push:
    branches: ["master"]

jobs:
  coverage-badge:
    name: Update Coverage and Tests Passing Badge

    runs-on: ubuntu-latest

    steps:
      - name: Check-out repository
        uses: actions/checkout@v4
      - name: Install latest version of uv
        uses: astral-sh/setup-uv@v6
      - name: Setup uv and install dependencies
        run: |
          uv venv
          uv sync --dev
      - name: Run Coverage
        run: |
          uv run pytest --cov daindex tests
          echo "COVERAGE=$(uv run coverage report --format markdown --precision 1 | awk -F'|' 'END{gsub(/ *(\*\*|%)* */, "", $(NF-1)); print $(NF-1)}')" >> $GITHUB_ENV
      - name: Create Coverage Badge
        uses: schneegans/dynamic-badges-action@v1.7.0
        with:
          auth: ${{ secrets.GIST_SECRET }}
          gistID: 980a5940c78997c3c75164953475a0dc
          filename: coverage.json
          label: test coverage
          message: ${{ env.COVERAGE }}%
          valColorRange: ${{ env.COVERAGE }}
          minColorRange: 0
          maxColorRange: 100
      - name: Run Tests
        run: |
          echo "COLLECTED=$(uv run pytest --collect-only | grep -m 1 "collected" | awk '{print $2;}' | tr -d '[:space:]\n')" >> $GITHUB_ENV
          echo "PASSED=$(uv run pytest --verbose | grep -o "PASSED" | wc -l | tr -d '[:space:]\n')" >> $GITHUB_ENV
      - name: Create Tests Passing Badge
        uses: schneegans/dynamic-badges-action@v1.7.0
        with:
          auth: ${{ secrets.GIST_SECRET }}
          gistID: 980a5940c78997c3c75164953475a0dc
          filename: tests.json
          label: tests passing
          message: ${{ env.PASSED }} / ${{ env.COLLECTED }}
          valColorRange: ${{ env.PASSED }}
          minColorRange: 0
          maxColorRange: ${{ env.COLLECTED }}
  update-badges:
    name: Update CLOC Badges

    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Download cloc
        run: sudo apt-get update -y && sudo apt-get install -y cloc
      - name: Get the Numbers
        run: |
          echo "CODE_LINES=$(.github/cloc.sh --loc)" >> $GITHUB_ENV
          echo "COMMENT_PERCENTAGE=$(.github/cloc.sh --percentage)" >> $GITHUB_ENV
      - name: Create Lines-of-Code Badge
        uses: schneegans/dynamic-badges-action@v1.7.0
        with:
          auth: ${{ secrets.GIST_SECRET }}
          gistID: 980a5940c78997c3c75164953475a0dc
          filename: loc.json
          label: lines of code
          message: ${{ env.CODE_LINES }}
          color: blue
      - name: Create Comments Badge
        uses: schneegans/dynamic-badges-action@v1.7.0
        with:
          auth: ${{ secrets.GIST_SECRET }}
          gistID: 980a5940c78997c3c75164953475a0dc
          filename: comments.json
          label: comment percentage
          message: ${{ env.COMMENT_PERCENTAGE }}%
          valColorRange: ${{ env.COMMENT_PERCENTAGE }}
          maxColorRange: 40
          minColorRange: 0
