name: Tests

on:
  pull_request:
  push:
    branches:
      - dev
      - main

jobs:
  test:
    name: test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - uses: actions/checkout@v4

      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@v6

      - name: Install tox
        run: uv tool install --python-preference only-managed --python 3.13 tox --with tox-uv

      - name: Setup test suite
        run: tox run -vv --notest --skip-missing-interpreters false

      - name: Run test suite
        run: tox run --skip-pkg-install
